Models/ContatoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Cadastro.Models
{
    public class ContatoModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Digite o nome do contato!")]
        public string Nome { get; set;}
        [Required(ErrorMessage = "Digite o e-mail do contato!")]
        [EmailAddress(ErrorMessage = "O e-mail informado não é válido")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Digite o celular do contato!")]
        [Phone(ErrorMessage ="O celular informado não é válido!")]
        public string Celular { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Cadastro.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/PerfilEnum.cs
namespace Cadastro.Models
{
    public class PerfilEnum
    {
        public int Id { get; set; }
    }
}

Models/UsuarioModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cadastro.Models
{
    public class UsuarioModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Login { get; set; }
        public string Email { get; set; }
        public PerfilEnum Perfil { get; set; }
        public string Senha { get; set; }
        public DateTime DataCadastro { get; set; }
        public DateTime? DataAtualizacao { get; set; }
    }
}

Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cadastro.Models;
using Cadastro.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace Cadastro.Controllers
{
    public class ContatoController : Controller
    {
        private readonly IContatoRepositorio _contatoRepositorio;
        public ContatoController(IContatoRepositorio contatoRepositorio)
        {
            _contatoRepositorio = contatoRepositorio;
        }

        public IActionResult Index()
        {
            List<ContatoModel> contatos = _contatoRepositorio.BuscarTodos();
            return View(contatos);
        }

        public IActionResult Criar(int id)
        {

            return View();
        }

        public IActionResult Editar(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);
            return View(contato);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);
            return View(contato);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _contatoRepositorio.Apagar(id);
                if(apagado){
                    TempData["MensagemSucesso"] = "Contato apagado com sucesso";
                }
                else
                {
                    TempData["MensagemErro"] = "Ops! Não Conseguimos apagar o contato";
                }
                return RedirectToAction("Index");
            }
            catch (System.Exception)
            {
                TempData["MensagemErro"] = "Ops! Não Conseguimos apagar o contato";
                return RedirectToAction("Index");
            }
            
        }
        [HttpPost]
        public IActionResult Criar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contatoRepositorio.Adicionar(contato);
                    TempData["MensagemSucesso"] = "Contato cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(contato);
            }

            catch (System.Exception erro)
            {
                TempData["MensagemSucesso"] = $"Ops! Não conseguimos cadastrar seu contato, tente novamente! Detalhe do erro: `{erro.Message}";
                return RedirectToAction("Index");
            }
            
            return View(contato);
        }
        [HttpPost]
        public IActionResult Alterar(ContatoModel contato)
        {
            try
            {
                 if (ModelState.IsValid)
                {
                    _contatoRepositorio.Atualizar(contato);
                    TempData["MensagemSucesso"] = "Contato alterado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View("Editar", contato);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, nao conseguimos cadastrar";
                return RedirectToAction("Index");
            }
           
            
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Cadastro.Models;

namespace Cadastro.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cadastro.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace Cadastro.Controllers
{
    public class UsuarioController : Controller
    {

        private readonly IUsuarioRepositorio _usuarioRepositorio;

        public UsuarioController(IUsuarioRepositorio usuarioRepositorio)
        {
            _usuarioRepositorio = usuarioRepositorio;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Contato/ApagarConfirmacao.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Apagar";
}

<div>
    <h1>Você quer mesmo apagar o contato (@Model.Nome)?</h1>
    <br />
    <br />
    <div class="d-grid gap-2 col-6 mx-auto">
        <a class="btn btn-danger" type="button" asp-action="Apagar" asp-route-id="@Model.Id" asp-controller="Contato" role="button">Apagar</a>
        <a class="btn btn-secondary" type="button"  asp-controller="Contato" asp-action="Index" role="button">Cancelar</a>
    </div>
</div>


Views/Contato/Criar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Cadastrar Contato";
}

<div>
    <h1>Cadastrar Contato</h1>
</div>

<form asp-controller="Contato" asp-action="Criar" method="post">
    <div class="mb-6">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Nome">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>
    <div class="mb-6">
        <label for="email" class="form-label">Email</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="E-mail">
        @Html.ValidationMessageFor(x => x.Email)
    </div>
    <div class="mb-6">
        <label for="celular" class="form-label">Celular</label>
        <input type="text" asp-for="Celular" class="form-control" placeholder="Celular">
        @Html.ValidationMessageFor(x => x.Celular)
    </div>
    <button  type="submit" class="mb-4 btn btn-primary">Adicionar</button>
    
    <a class="btn btn-secondary btn-sm" asp-controller="Contato" asp-action="Index">Voltar</a>
</form>



Views/Contato/Editar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Editar Contato";
}


<div>
    <h1>Cadastrar Contato</h1>
</div>

<form asp-controller="Contato" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id" />
    <div class="my-4">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Nome">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="my-4">
        <label for="email" class="form-label">Email</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="E-mail">
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="my-4">
        <label for="celular" class="form-label">Celular</label>
        <input type="text" asp-for="Celular" class="form-control" placeholder="Celular">
        @Html.ValidationMessageFor(x => x.Celular)
    </div>

    <button type="submit" class="btn btn-primary mt-3">Alterar</button>
    <input type="button" class="btn btn-primary mt-3" value="Gerar PDF">
    <a class="btn btn-secondary btn-sm mt-3" asp-controller="Contato" asp-action="Index">Voltar</a>
</form>


Views/Contato/Index.cshtml
@model List<ContatoModel>
@{
    ViewData["Title"] = "Listagem de Contato";
}

<h1>Listagem de Contatos</h1>

<div class="">
    <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar">Adicionar Novo Contato</a>
</div>
@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
<div class="alert alert-danger" role="alert">
    <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="close">X</button>
    @TempData["MensagemErro"]
</div>
}

<table class="table" id="table-contatos">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Email</th>
            <th scope="col">Celular</th>
            <th scope="col">Opções</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (ContatoModel contato in Model)
            {
                <tr>
                    <th scope="row">@contato.Id</th>
                    <td>@contato.Nome</td>
                    <td>@contato.Email</td>
                    <td>@contato.Celular</td>
                    <td>
                        <a class="btn btn-warning" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="Editar">Editar</a>
                        <a class="btn btn-danger" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="ApagarConfirmacao">Apagar</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>


Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
  
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "RegisterSystem";
}

<div class="">
    <h1>Bem Vindo!</h1>
    <p>Sistema de controle de contatos</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cadastro</title>
        <link rel="stylesheet" type="text/css" href="~/lib/datatables/css/datatables.min.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="~/css/site.css" />           
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Cadastro</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Início</a></li>
                    <li><a asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a></li>
                    <li><a asp-area="" asp-controller="Usuario" asp-action="Index">Usuários</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2022 - Cadastro</p>
        </footer>
    </div>

    
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script type="text/javascript" src="~/lib/datatables/js/datatables.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>

    

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Usuario/Index.cshtml
@model List<UsuarioModel>
@{
    ViewData["Title"] = "Listagem de Usuarios";
}

<h1>Listagem de Usuarios</h1>

<div class="">
    <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar">Adicionar Novo Usuario</a>
</div>
@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
<div class="alert alert-danger" role="alert">
    <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="close">X</button>
    @TempData["MensagemErro"]
</div>
}

<table class="table-usuarios" id="table-usuarios">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Login</th>
            <th scope="col">Email</th>
            <th scope="col">Data de cadastro</th>
            <th scope="col">Opções</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (var usuario in Model)
            {
                <tr>
                    <th scope="row">@usuario.Id</th>
                    <td>@usuario.Nome</td>
                    <td>@usuario.Login</td>
                    <td>@usuario.Email</td>
                    <td>@usuario.DataCadastro</td>
                    <td>
                        <a class="btn btn-warning" asp-route-id="@usuario.Id" asp-controller="Usuario" asp-action="Editar">Editar</a>
                        <a class="btn btn-danger" asp-route-id="@usuario.Id" asp-controller="Usuario" asp-action="ApagarConfirmacao">Apagar</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
